# ===============================
# = Application Configuration
# ===============================
spring.application.name=Plant Manager
server.port=8080

# ===============================
# = Datasource Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/plant-manager
spring.datasource.username=ronald
spring.datasource.password=ronald2003
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = JPA / Hibernate Configuration
# ===============================
# Afficher les requêtes SQL dans la console
spring.jpa.show-sql=true

# Hibernate ddl-auto options:
# none / validate / update / create / create-drop
spring.jpa.hibernate.ddl-auto=update

# Dialect PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# = Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

jwt.expiration.ms=36000000

# ===============================
# = Internationalization (optionnel)
# ===============================
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# ===============================
# = JSON Serialization (optionnel)
# ===============================
spring.jackson.serialization.indent_output=true
